
================================================================================
ClusterNotAttemptedVmInfo
================================================================================


.. describe:: Property of
    
    :py:class:`~pyvisdk.do.cluster_power_on_vm_result.ClusterPowerOnVmResult`
    
.. describe:: See also
    
    :py:class:`~pyvisdk.do.localized_method_fault.LocalizedMethodFault`,
    :py:class:`~pyvisdk.do.virtual_machine.VirtualMachine`
    
.. describe:: Since
    
    VI API 2.5
    
.. describe:: Extends
    
    :py:class:`~pyvisdk.mo.dynamic_data.DynamicData`
    
.. class:: pyvisdk.do.cluster_not_attempted_vm_info.ClusterNotAttemptedVmInfo
    
    .. py:attribute:: fault
    
        The exception returned.
        
    
    .. py:attribute:: vm
    
        The virtual machine that can not be powered on.
        
    